# Generated by Django 3.2 on 2021-04-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museumapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='offer',
            field=models.BooleanField(default=False),
        ),
    ]
